# Generated by Django 4.2.13 on 2024-05-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brokeriai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vardas", models.CharField(max_length=100)),
                ("pavarde", models.CharField(max_length=100)),
                ("imones_pavadinimas", models.CharField(max_length=100)),
                ("el_pastas", models.EmailField(max_length=254)),
                ("tel_numeris", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Klientai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vardas", models.CharField(max_length=100)),
                ("pavarde", models.CharField(max_length=100)),
                ("tel_numeris", models.IntegerField()),
                ("gimimo_data", models.DateField()),
                ("adresas", models.TextField()),
                ("el_pastas", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Paslaugos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pavadinimas", models.CharField(max_length=100)),
                ("aprasymas", models.TextField()),
                ("kaina", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Polisai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poliso_tipas", models.CharField(max_length=100)),
                ("pradzios_data", models.DateField()),
                ("pabaigos_data", models.DateField()),
                ("draudimo_suma", models.FloatField()),
                ("iskaita", models.FloatField()),
                ("apsauga", models.TextField()),
                (
                    "brokeriai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polisai",
                        to="app.brokeriai",
                    ),
                ),
                (
                    "klientai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polisai",
                        to="app.klientai",
                    ),
                ),
                (
                    "paslaugos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polisai",
                        to="app.paslaugos",
                    ),
                ),
            ],
        ),
    ]
