# Generated by Django 4.2.13 on 2024-05-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polisai",
            name="apsauga",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="polisai",
            name="brokeriai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="polisai",
                to="app.brokeriai",
            ),
        ),
        migrations.AlterField(
            model_name="polisai",
            name="poliso_tipas",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
