# Generated by Django 4.2.13 on 2024-05-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_polisai_apsauga_alter_polisai_brokeriai_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polisai",
            name="draudimo_suma",
            field=models.FloatField(default=100000),
        ),
        migrations.AlterField(
            model_name="polisai",
            name="iskaita",
            field=models.FloatField(default=0),
        ),
    ]
