# Generated by Django 4.2.13 on 2024-05-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_klientai_user_alter_polisai_iskaita"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polisai",
            name="iskaita",
            field=models.FloatField(default=0),
        ),
    ]
