# Generated by Django 4.2.13 on 2024-05-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_country_remove_klientai_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="continent",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="country",
            name="latitude",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="country",
            name="longitude",
            field=models.FloatField(default=1),
        ),
    ]
