# Generated by Django 4.2.13 on 2024-05-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_country_continent_alter_country_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polisai",
            name="apsauga",
            field=models.CharField(
                blank=True,
                choices=[
                    ("medicinines_islados", "Medicininės išlaidos"),
                    ("nelaimingi_atsitikimai", "Nelaimingi atsitikimai"),
                    ("civiline_atsakomybe", "Civilinė atsakomybė"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="polisai",
            name="draudimo_suma",
            field=models.IntegerField(
                choices=[(100000, "100,000"), (300000, "300,000"), (500000, "500,000")],
                default=100000,
            ),
        ),
        migrations.AlterField(
            model_name="polisai",
            name="iskaita",
            field=models.IntegerField(
                choices=[(0, "0"), (50, "50"), (80, "80"), (100, "100"), (120, "120")],
                default=0,
            ),
        ),
    ]
