# Generated by Django 4.2.13 on 2024-05-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_polisai_apsauga_alter_polisai_draudimo_suma_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polisai",
            name="apsauga",
            field=models.CharField(
                choices=[
                    ("medicinines_islados", "Medicininės išlaidos"),
                    ("nelaimingi_atsitikimai", "Nelaimingi atsitikimai"),
                    ("civiline_atsakomybe", "Civilinė atsakomybė"),
                ],
                max_length=50,
            ),
        ),
    ]
