# Generated by Django 4.2.13 on 2024-05-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_klientai_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klientai",
            name="tel_numeris",
            field=models.IntegerField(blank=True),
        ),
    ]
