# Generated by Django 4.2.13 on 2024-05-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_klientai_tel_numeris"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klientai",
            name="tel_numeris",
            field=models.CharField(max_length=15),
        ),
    ]
