# Generated by Django 4.2.13 on 2024-05-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_klientai_tel_numeris"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klientai",
            name="adresas",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="klientai",
            name="el_pastas",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="klientai",
            name="gimimo_data",
            field=models.DateField(blank=True),
        ),
    ]
