# Generated by Django 4.2.13 on 2024-06-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_klientai_adresas_alter_klientai_el_pastas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klientai",
            name="gimimo_data",
            field=models.DateField(null=True),
        ),
    ]
