# Generated by Django 4.2.13 on 2024-06-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_brokeriai_el_pastas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polisai",
            name="paslaugos",
            field=models.ForeignKey(
                default="Kelionių draudimas",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polisai",
                to="app.paslaugos",
            ),
        ),
    ]
