# Generated by Django 4.2.13 on 2024-06-03 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0021_alter_polisai_paslaugos"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        default="default-broker.png", upload_to="broker_pics"
                    ),
                ),
                (
                    "broker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.brokeriai"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
