# Generated by Django 4.2.13 on 2024-06-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_brokerprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_level", models.CharField(max_length=100)),
                ("kof", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Cover1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("na_sum", models.FloatField()),
                ("na_kof", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Cover2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("civ_sum", models.FloatField()),
                ("civ_kof", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Cover3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("med_sum", models.FloatField()),
                ("med_kof", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Iskaita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum", models.FloatField()),
                ("kof", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TravelMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("kof", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="country",
            name="risk_level",
        ),
        migrations.AddField(
            model_name="country",
            name="link",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="polisai",
            name="country",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.country"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="brokeriai",
            name="tel_numeris",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="polisai",
            name="paslaugos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polisai",
                to="app.paslaugos",
            ),
        ),
        migrations.CreateModel(
            name="Apsauga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apsauga",
                        to="app.cover1",
                    ),
                ),
                (
                    "cover2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apsauga",
                        to="app.cover2",
                    ),
                ),
                (
                    "cover3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apsauga",
                        to="app.cover3",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="country",
            name="country_risk",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries",
                to="app.countryrisk",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="polisai",
            name="travel_mode",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.travelmode",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="polisai",
            name="apsauga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.apsauga"
            ),
        ),
        migrations.AlterField(
            model_name="polisai",
            name="iskaita",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.iskaita"
            ),
        ),
    ]
