# Generated by Django 4.2.13 on 2024-06-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_countryrisk_cover1_cover2_cover3_iskaita_travelmode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="map_risk",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
