# Generated by Django 4.2.13 on 2024-06-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_country_map_risk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="country_risk",
        ),
    ]
