# Generated by Django 4.2.13 on 2024-06-04 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_remove_country_country_risk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="polisai",
            name="apsauga",
        ),
        migrations.AddField(
            model_name="polisai",
            name="cover1",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.cover1"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="polisai",
            name="cover2",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.cover2"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="polisai",
            name="cover3",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.cover3"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Apsauga",
        ),
    ]
