# Generated by Django 4.2.13 on 2024-06-04 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_remove_polisai_draudimo_suma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polisai",
            name="paslaugos",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polisai",
                to="app.paslaugos",
            ),
        ),
    ]
