# Generated by Django 4.2.13 on 2024-06-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_alter_polisai_paslaugos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paslaugos",
            name="pavadinimas",
            field=models.CharField(default="Kelionių draudimas", max_length=100),
        ),
    ]
