# Generated by Django 4.2.13 on 2024-06-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_alter_paslaugos_pavadinimas"),
    ]

    operations = [
        migrations.AddField(
            model_name="polisai",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
