# Generated by Django 4.2.13 on 2024-06-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_polisai_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokerprofile",
            name="company",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
