# Generated by Django 4.2.13 on 2024-06-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_brokerprofile_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brokerprofile",
            name="company",
        ),
    ]
