# Generated by Django 4.2.13 on 2024-06-05 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_remove_brokerprofile_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polisai",
            name="cover1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.cover1",
            ),
        ),
        migrations.AlterField(
            model_name="polisai",
            name="cover2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.cover2",
            ),
        ),
    ]
