COUNTRY_RISK_LEVELS = {
    'high': [
        'Afghanistan', 'Iraq', 'Syria', 'Yemen', 'Somalia',
        'Libya', 'South Sudan', 'Mali', 'Central African Republic'
    ],
    'medium': [
        'Brazil', 'India', 'Philippines', 'Egypt', 'Colombia',
        'Pakistan', 'Turkey', 'Thailand', 'Mexico', 'Ukraine'
    ],
    'low': [
        'Canada', 'Australia', 'Germany', 'Japan', 'United Kingdom',
        'France', 'Italy', 'Spain', 'Netherlands', 'Sweden'
    ],
}

# Country surcharges (example countries)

COUNTRY_SURCHARGES = {
    'high': 50.0,
    'medium': 30.0,
    'low': 10.0,
}
list ={
    'Afghanistan': 'high_risk_country',
    'Albania': 'medium_risk_country',
    'Algeria': 'high_risk_country',
    'Andorra': 'low_risk_country',
    'Angola': 'medium_risk_country',
    'Antigua and Barbuda': 'low_risk_country',
    'Argentina': 'medium_risk_country',
    'Armenia': 'medium_risk_country',
    'Australia': 'low_risk_country',
    'Austria': 'low_risk_country',
    'Azerbaijan': 'medium_risk_country',
    'Bahamas': 'low_risk_country',
    'Bahrain': 'medium_risk_country',
    'Bangladesh': 'high_risk_country',
    'Barbados': 'low_risk_country',
    'Belarus': 'medium_risk_country',
    'Belgium': 'low_risk_country',
    'Belize': 'medium_risk_country',
    'Benin': 'medium_risk_country',
    'Bhutan': 'medium_risk_country',
    'Bolivia': 'medium_risk_country',
    'Bosnia and Herzegovina': 'medium_risk_country',
    'Botswana': 'medium_risk_country',
    'Brazil': 'medium_risk_country',
    'Brunei': 'low_risk_country',
    'Bulgaria': 'medium_risk_country',
    'Burkina Faso': 'high_risk_country',
    'Burundi': 'high_risk_country',
    'Cabo Verde': 'medium_risk_country',
    'Cambodia': 'medium_risk_country',
    'Cameroon': 'medium_risk_country',
    'Canada': 'low_risk_country',
    'Central African Republic': 'high_risk_country',
    'Chad': 'high_risk_country',
    'Chile': 'medium_risk_country',
    'China': 'medium_risk_country',
    'Colombia': 'medium_risk_country',
    'Comoros': 'high_risk_country',
    'Congo (Congo-Brazzaville)': 'medium_risk_country',
    'Costa Rica': 'medium_risk_country',
    'Croatia': 'low_risk_country',
    'Cuba': 'high_risk_country',
    'Cyprus': 'low_risk_country',
    'Czechia (Czech Republic)': 'low_risk_country',
    'Democratic Republic of the Congo': 'high_risk_country',
    'Denmark': 'low_risk_country',
    'Djibouti': 'high_risk_country',
    'Dominica': 'medium_risk_country',
    'Dominican Republic': 'medium_risk_country',
    'East Timor (Timor-Leste)': 'medium_risk_country',
    'Ecuador': 'medium_risk_country',
    'Egypt': 'high_risk_country',
    'El Salvador': 'medium_risk_country',
    'Equatorial Guinea': 'medium_risk_country',
    'Eritrea': 'high_risk_country',
    'Estonia': 'low_risk_country',
    'Eswatini (fmr. "Swaziland")': 'medium_risk_country',
    'Ethiopia': 'high_risk_country',
    'Fiji': 'medium_risk_country',
    'Finland': 'low_risk_country',
    'France': 'low_risk_country',
    'Gabon': 'medium_risk_country',
    'Gambia': 'medium_risk_country',
    'Georgia': 'medium_risk_country',
    'Germany': 'low_risk_country',
    'Ghana': 'medium_risk_country',
    'Greece': 'low_risk_country',
    'Grenada': 'low_risk_country',
    'Guatemala': 'medium_risk_country',
    'Guinea': 'medium_risk_country',
    'Guinea-Bissau': 'high_risk_country',
    'Guyana': 'medium_risk_country',
    'Haiti': 'high_risk_country',
    'Honduras': 'medium_risk_country',
    'Hungary': 'low_risk_country',
    'Iceland': 'low_risk_country',
    'India': 'medium_risk_country',
    'Indonesia': 'medium_risk_country',
    'Iran': 'high_risk_country',
    'Iraq': 'high_risk_country',
    'Ireland': 'low_risk_country',
    'Israel': 'medium_risk_country',
    'Italy': 'low_risk_country',
    'Ivory Coast': 'medium_risk_country',
    'Jamaica': 'medium_risk_country',
    'Japan': 'low_risk_country',
    'Jordan': 'medium_risk_country',
    'Kazakhstan': 'medium_risk_country',
    'Kenya': 'medium_risk_country',
    'Kiribati': 'medium_risk_country',
    'Kosovo': 'medium_risk_country',
    'Kuwait': 'medium_risk_country',
    'Kyrgyzstan': 'medium_risk_country',
    'Laos': 'medium_risk_country',
    'Latvia': 'low_risk_country',
    'Lebanon': 'medium_risk_country',
    'Lesotho': 'medium_risk_country',
    'Liberia': 'high_risk_country',
    'Libya': 'high_risk_country',
    'Liechtenstein': 'low_risk_country',
    'Lithuania': 'low_risk_country',
    'Luxembourg': 'low_risk_country',
    'Madagascar': 'medium_risk_country',
    'Malawi': 'medium_risk_country',
    'Malaysia': 'medium_risk_country',
    'Maldives': 'medium_risk_country',
    'Mali': 'medium_risk_country',
    'Malta': 'low_risk_country',
    'Marshall Islands': 'low_risk_country',
    'Mauritania': 'medium_risk_country',
    'Mauritius': 'medium_risk_country',
    'Mexico': 'medium_risk_country',
    'Micronesia': 'medium_risk_country',
    'Moldova': 'medium_risk_country',
    'Monaco': 'low_risk_country',
    'Mongolia': 'medium_risk_country',
    'Montenegro': 'medium_risk_country',
    'Morocco': 'medium_risk_country',
    'Mozambique': 'medium_risk_country',
    'Myanmar (formerly Burma)': 'medium_risk_country',
    'Namibia': 'medium_risk_country',
    'Nauru': 'low_risk_country',
    'Nepal': 'medium_risk_country',
    'Netherlands': 'low_risk_country',
    'New Zealand': 'low_risk_country',
    'Nicaragua': 'medium_risk_country',
    'Niger': 'high_risk_country',
    'Nigeria': 'medium_risk_country',
    'North Korea': 'high_risk_country',
}
